version: "3.9"

services:
  backend:
    build:
      context: ./city-airbackend
    container_name: air_backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./air_cityFrontend
    container_name: air_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend